### ISSUE TITLE
skin i18n & customization

### ISSUE THREAD

**Issue by pmh-only** [pmh-only/Neptune#4]
There are lots of hard coded Korean texts.

This issue replaces hard coded text to i18n & customizable text.

## Tasks
- [x] site title customization
- [ ] #5
- [ ] right navigation items customization & i18n
- [ ] skin primary color customization
